language: python
python:
  - '3.9'
install:
  - pip install -r requirements.txt
script:
  - python3 -m pytest -v tests/test_dice.py
deploy: &heroku
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app:
    main: ci-homework-stage-fvp
    production: ci-homework-prod-fvp